exclude: |
  (?x)^(
      web/dist|
      web/node_modules
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: name-tests-test
  - id: requirements-txt-fixer

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
